# Generated by Django 5.1.2 on 2024-10-17 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.engineer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'unique_together': {('engineer', 'date')},
            },
        ),
    ]
